# Generated by Django 5.1.3 on 2024-12-03 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fantasy', 'Fantasy'), ('History', 'History'), ('Politic', 'Politic'), ('Science Fiction', 'Science Fiction')], max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.book')),
            ],
        ),
    ]
